'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { Activity, ArrowRight, CalendarDays, Check, ChevronDown, Clock3, FileUp, FlaskConical, HeartPulse, MapPin, Menu, Search, ShieldCheck, ShoppingCart, Stethoscope, UserRound, Video, X } from 'lucide-react';
import styles from './page.module.css';
import { UserAuthButton } from '../components/UserAuthButton';
import { SafeImage } from '../components/SafeImage';
import { useCartStore } from '../lib/useCartStore';

type Product = { id: string; name: string; composition: string; price: number; mrp: number; brand: string; category: string; image: string; rx?: boolean; };
const image = '/assets/product-placeholder.svg';
const products: Product[] = [
    { id: 'dolo', name: 'Dolo 650mg Tablet', composition: 'Paracetamol 650mg', price: 32, mrp: 38, brand: 'Micro Labs', category: 'Pain relief', image },
    { id: 'calpol', name: 'Calpol 650mg Tablet', composition: 'Paracetamol 650mg', price: 28, mrp: 35, brand: 'GlaxoSmithKline', category: 'Pain relief', image },
    { id: 'azithral', name: 'Azithral 500mg Tablet', composition: 'Azithromycin 500mg', price: 112, mrp: 128, brand: 'Alembic', category: 'Antibiotics', image, rx: true },
    { id: 'cetirizine', name: 'Cetirizine 10mg Tablet', composition: 'Cetirizine 10mg', price: 19, mrp: 24, brand: 'Dr Reddy’s', category: 'Allergy care', image },
    { id: 'shelcal', name: 'Shelcal 500mg Tablet', composition: 'Calcium Carbonate 500mg', price: 104, mrp: 120, brand: 'Torrent', category: 'Vitamins', image },
];
const doctors = [{ name: 'Dr. Meera Sharma', specialty: 'General Physician', exp: '14 yrs', rating: '4.9', fee: 399 }, { name: 'Dr. Rohan Kapoor', specialty: 'Dermatologist', exp: '11 yrs', rating: '4.8', fee: 599 }];

let uploaded = false;
const setUploaded = (value: boolean) => { uploaded = value; };

export default function Home() {
    const [query, setQuery] = useState(''); const [tab, setTab] = useState('Medicines'); const [notice, setNotice] = useState(''); const [pin, setPin] = useState(''); const [uploaded, setUploaded] = useState(false); const cart = useCartStore((state) => state.items); const addItem = useCartStore((state) => state.addItem); const toggleCart = useCartStore((state) => state.toggleCart);
    const filtered = useMemo(() => products.filter(p => `${p.name} ${p.composition}`.toLowerCase().includes(query.toLowerCase())), [query]);
    const substitutes = products.filter(p => p.composition === 'Paracetamol 650mg');
    const add = (p: Product) => { addItem(p); setNotice(`${p.name} added to cart`); setTimeout(() => setNotice(''), 2200); };
    return <main className={styles.app}>
        <div className={styles.topline}>India&apos;s most trusted healthcare platform <span>Download the app</span></div>
        <header className={styles.header}><div className={styles.nav}><button className={styles.mobileMenu}><Menu size={20} /></button><Link href="/" className={styles.logo}><span>1</span>mg</Link><nav><button className={tab === 'Medicines' ? styles.activeNav : ''} onClick={() => setTab('Medicines')}>Medicines</button><button onClick={() => setTab('Lab Tests')}>Lab Tests</button><button onClick={() => setTab('Doctors')}>Consult Doctors</button></nav><div className={styles.location}><MapPin size={16} /><span>Deliver to <b>110001</b></span><ChevronDown size={14} /></div><UserAuthButton /><button className={styles.cart} onClick={toggleCart} aria-label="Open cart"><ShoppingCart size={19} /><i>{cart.length}</i></button></div><div className={styles.searchWrap}><Search size={20} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search for medicines and health products" /><kbd>⌘ K</kbd></div></header>
        {notice && <div className={styles.toast}>{notice}<X size={15} onClick={() => setNotice('')} /></div>}
        {tab === 'Medicines' && <>
            <section className={styles.hero}><div><p className={styles.eyebrow}>YOUR HEALTH, OUR PRIORITY</p><h1>Care that comes<br /><em>home.</em></h1><p className={styles.heroCopy}>Authentic medicines, lab tests and expert care delivered to your door.</p><button className={styles.primary} onClick={() => document.getElementById('catalog')?.scrollIntoView({ behavior: 'smooth' })}>Explore medicines <ArrowRight size={17} /></button></div><div className={styles.heroArt}><div className={styles.sun}></div><div className={styles.bottle}><span>1mg</span><small>DAILY<br />WELLNESS</small></div><div className={styles.heart}>♥</div></div></section>
            <section className={styles.services}><div><ShieldCheck /><b>100% genuine medicines</b><span>Quality you can trust</span></div><div><Activity /><b>Free doctor consultation</b><span>Get expert medical advice</span></div><div><Clock3 /><b>Care at your doorstep</b><span>Same-day delivery available</span></div></section>
            <section className={styles.content} id="catalog"><div className={styles.sectionHead}><div><p className={styles.eyebrow}>CURATED FOR YOU</p><h2>Shop by health concern</h2></div><button className={styles.linkBtn}>View all <ArrowRight size={15} /></button></div><div className={styles.categories}><button><span className={styles.catIcon}>◌</span><b>Everyday care</b><small>From ₹19</small></button><button><span className={styles.catIcon}>✚</span><b>Vitamins & nutrition</b><small>Up to 25% off</small></button><button><span className={styles.catIcon}>⌁</span><b>Cold & cough</b><small>Feel better, faster</small></button><button><span className={styles.catIcon}>◒</span><b>Skin care</b><small>Dermatologist picks</small></button></div>
                <div className={styles.sectionHead}><div><p className={styles.eyebrow}>POPULAR TODAY</p><h2>Medicines for every need</h2></div><span className={styles.muted}>Showing {filtered.length} products</span></div><div className={styles.productGrid}>{filtered.map(p => <article className={styles.product} key={p.id}><div className={styles.productImage}><SafeImage src={p.image} alt={p.name} width={120} height={140} style={{ objectFit: 'contain' }} />{p.rx && <span className={styles.rx}>Rx</span>}</div><p className={styles.productBrand}>{p.brand}</p><h3>{p.name}</h3><p className={styles.composition}>{p.composition}</p><div className={styles.price}>₹{p.price} <del>₹{p.mrp}</del><span>{Math.round((1 - p.price / p.mrp) * 100)}% off</span></div><button className={styles.addBtn} onClick={() => add(p)}>Add to cart</button></article>)}</div>
            </section>
            <section className={styles.substitute}><div><p className={styles.eyebrow}>SMARTER SAVINGS</p><h2>Find a lower-cost substitute</h2><p>Same active ingredient. Better value. Compare trusted alternatives recommended by our pharmacists.</p><button className={styles.darkBtn} onClick={() => setNotice('Substitute engine found 1 lower-cost option')}>Compare substitutes <ArrowRight size={16} /></button></div><div className={styles.compare}><div className={styles.compareLabel}>PARACETAMOL 650MG</div>{substitutes.slice(0, 2).map((p, i) => <div className={styles.compareRow} key={p.id}><div className={styles.miniPack}>1mg</div><div><b>{p.name}</b><small>{p.brand} · Same composition</small></div><strong>₹{p.price}</strong>{i === 1 && <span className={styles.best}>BEST VALUE</span>}</div>)}</div></section>
        </>}
        {tab === 'Lab Tests' && <Lab pin={pin} setPin={setPin} setNotice={setNotice} />} {tab === 'Doctors' && <Doctors setNotice={setNotice} />}
        <section className={styles.footerCta}><div><HeartPulse size={26} /><b>Health stories, made simple.</b><span>Join 10 million+ people who trust 1mg for their health.</span></div><button className={styles.primary}>Get the app <ArrowRight size={16} /></button></section>
        <footer><div className={styles.logo}><span>1</span>mg</div><span>© 2026 Tata 1mg · Care for all.</span><div>Privacy &nbsp; Terms &nbsp; Contact us</div></footer>
    </main>;
}
function Lab({ pin, setPin, setNotice }: { pin: string; setPin: (v: string) => void; setNotice: (v: string) => void }) { return <section className={styles.content + ' ' + styles.module}><div className={styles.moduleHero}><div><p className={styles.eyebrow}>DIAGNOSTICS, MADE EASY</p><h1>Know your health.<br /><em>Own your life.</em></h1><p>Book reliable lab tests with free home sample collection and digital reports.</p></div><div className={styles.labArt}><FlaskConical size={80} /></div></div><div className={styles.sectionHead}><div><p className={styles.eyebrow}>POPULAR PACKAGES</p><h2>Tests people love</h2></div><span className={styles.muted}>Free home collection</span></div><div className={styles.testGrid}>{['Full Body Checkup', 'Thyroid Profile', 'Diabetes Care', 'Vitamin Health'].map((name, i) => <article className={styles.test} key={name}><span><FlaskConical size={20} /></span><h3>{name}</h3><p>{i + 18} parameters covered</p><b>₹{699 + i * 200}</b><button className={styles.addBtn} onClick={() => setNotice(`${name} selected`)}>Book now <ArrowRight size={15} /></button></article>)}</div><div className={styles.pinCheck}><div><MapPin /><b>Check home collection</b><span>Enter your pincode to see available slots</span></div><input placeholder="Enter pincode" value={pin} onChange={e => setPin(e.target.value)} /><button className={styles.darkBtn} onClick={() => setNotice(pin.length === 6 ? 'Great, home collection is available' : 'Please enter a 6-digit pincode')}>Check</button></div></section> }
function Doctors({ setNotice }: { setNotice: (v: string) => void }) { return <section className={styles.content + ' ' + styles.module}><div className={styles.doctorHero}><div><p className={styles.eyebrow}>EXPERT CARE, ON CALL</p><h1>A doctor is<br /><em>always here.</em></h1><p>Talk to a qualified doctor in minutes, from wherever you are.</p><button className={styles.primary} onClick={() => setNotice('Showing doctors available now')}>Consult now <Video size={17} /></button></div><div className={styles.doctorArt}><Stethoscope size={86} /></div></div><div className={styles.sectionHead}><div><p className={styles.eyebrow}>TOP SPECIALISTS</p><h2>Find your doctor</h2></div><span className={styles.muted}>Available today</span></div><div className={styles.doctorGrid}>{doctors.map(d => <article className={styles.doctor} key={d.name}><div className={styles.avatar}>{d.name.split(' ').map(x => x[0]).join('')}</div><div><h3>{d.name}</h3><p>{d.specialty}</p><small>{d.exp} experience · ★ {d.rating}</small><div><b>₹{d.fee}</b><button className={styles.addBtn} onClick={() => setNotice(`Slot held with ${d.name}`)}>Book slot <CalendarDays size={15} /></button></div></div></article>)}</div><div className={styles.upload}><div><FileUp /><b>Need a prescription?</b><span>Upload it securely for verification by our pharmacists.</span></div><label className={styles.darkBtn}>{uploaded ? <><Check size={16} /> Uploaded</> : <>Upload prescription <input type="file" hidden onChange={() => setUploaded(true)} /></>}</label></div></section> }
