'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { Activity, ArrowRight, CalendarDays, Check, ChevronDown, Clock3, FileUp, FlaskConical, HeartPulse, Leaf, MapPin, Menu, Search, ShieldCheck, ShoppingCart, Stethoscope, UserRound, Video, X } from 'lucide-react';
import styles from './page.module.css';
import { UserAuthButton } from '../components/UserAuthButton';
import { SafeImage } from '../components/SafeImage';
import { useCartStore } from '../lib/useCartStore';
import OneMgProductCard from '../src/components/OneMg/OneMgProductCard';
import oneMgProducts from '../src/data/oneMgProducts';

type Product = { id: string; name: string; composition: string; price: number; mrp: number; brand: string; category: string; image: string; rx?: boolean; };
const image = '/assets/product-placeholder.svg';
const products: Product[] = [
    { id: 'dolo', name: 'Dolo 650mg Tablet', composition: 'Paracetamol 650mg', price: 32, mrp: 38, brand: 'Micro Labs', category: 'Pain relief', image },
    { id: 'calpol', name: 'Calpol 650mg Tablet', composition: 'Paracetamol 650mg', price: 28, mrp: 35, brand: 'GlaxoSmithKline', category: 'Pain relief', image },
    { id: 'azithral', name: 'Azithral 500mg Tablet', composition: 'Azithromycin 500mg', price: 112, mrp: 128, brand: 'Alembic', category: 'Antibiotics', image, rx: true },
    { id: 'cetirizine', name: 'Cetirizine 10mg Tablet', composition: 'Cetirizine 10mg', price: 19, mrp: 24, brand: 'Dr Reddy’s', category: 'Allergy care', image },
    { id: 'shelcal', name: 'Shelcal 500mg Tablet', composition: 'Calcium Carbonate 500mg', price: 104, mrp: 120, brand: 'Torrent', category: 'Vitamins', image },
];
const doctors = [{ name: 'Dr. Meera Sharma', specialty: 'General Physician', exp: '14 yrs', rating: '4.9', fee: 399 }, { name: 'Dr. Rohan Kapoor', specialty: 'Dermatologist', exp: '11 yrs', rating: '4.8', fee: 599 }];
const healthConcerns = [
    { name: 'Diabetes', href: 'https://www.1mg.com/categories/diabetes-1', image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=300&q=80' },
    { name: 'Heart Care', href: 'https://www.1mg.com/categories/heart-care-35', image: 'https://cdn.onmmd.gr/img/1200/900/90/2025/06/25/86e9fb4a-bigstock-Young-woman-in-pajamas-having-83143466.jpg?t=naytY2eR1b158SZ9AxSn1g' },
    { name: 'Stomach Care', href: 'https://www.1mg.com/categories/stomach-care-30', image: 'https://ysm-res.cloudinary.com/image/upload/c_fill,f_auto,g_faces:auto,h_960,q_auto,w_1280/v1/yms/prod/852eddc0-15e7-4878-8511-006118f58849' },
    { name: 'Liver Care', href: 'https://www.1mg.com/categories/health-conditions/liver-care-39', image: 'https://images.unsplash.com/photo-1584982751601-97dcc096659c?auto=format&fit=crop&w=300&q=80' },
    { name: 'Bone, Joint & Muscle Care', href: 'https://www.1mg.com/categories/health-conditions/bone-joint-muscle-care-34', image: 'https://www.proff-dolgit.de/Proff/Content/Gelenkschmerzen/Gelekschmerzen/14753/image-thumb__14753__WebStartImagePR/AdobeStock_1255443104_Vitaliy%20.3ad1e9a9.jpg' },
    { name: 'Kidney Care', href: 'https://www.1mg.com/categories/health-conditions/kidney-care-40', image: 'https://www.bupasalud.com.pa/sites/default/files/inline-images/como-limpiar-los-rinones-2.jpg' },
    { name: 'Derma Care', href: 'https://www.1mg.com/categories/health-conditions/derma-care-1183', image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=300&q=80' },
    { name: 'Respiratory Care', href: 'https://www.1mg.com/categories/exclusive/respiratory-care-14', image: 'https://www.ciplamed.com/-/media/ciplamed/contentmigration/resources/image/asthmaadultfemaleiss_9875_01413.jpg?updated=20221130173526' },
];
const ayurvedaHighlights = [
    { title: 'Ashwagandha', detail: 'Traditional herbal wellness', description: 'A revered adaptogenic herb used in classic wellness routines for balance, vitality and everyday resilience.', image: 'https://images.unsplash.com/photo-1515586000433-45406d8e6662?auto=format&fit=crop&w=500&q=80' },
    { title: 'Turmeric', detail: 'A golden kitchen staple', description: 'Known for its warm earthy aroma and vibrant colour, turmeric is a familiar addition to both cooking and self-care rituals.', image: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?auto=format&fit=crop&w=500&q=80' },
    { title: 'Aloe Vera', detail: 'Plant-powered skin care', description: 'This soothing succulent is cherished for its cooling gel and easy-to-love freshness in everyday skin rituals.', image: 'https://static.wixstatic.com/media/ad0cb5_2a24903de1f244f6b69395e78b749405~mv2_d_2478_1859_s_2.jpg/v1/fill/w_640,h_1296,al_c,q_90,enc_avif,quality_auto/ad0cb5_2a24903de1f244f6b69395e78b749405~mv2_d_2478_1859_s_2.jpg' },
    { title: 'Amla', detail: 'Indian gooseberry goodness', description: 'A tangy, vitamin-rich fruit often enjoyed in traditional Ayurvedic blends for nourishment and everyday wellness.', image: '/assets/amla-illustration.svg' },
];
const ayurvedaCareSections = [
    { title: 'Digestive Care', items: [
        { name: 'Alsi', description: 'Flax seeds are small oil-rich seeds with a mild, nutty taste. They are often roasted, ground, or stirred into everyday meals and drinks.', image: 'https://onemg.gumlet.io/images/qgyjmltpxtbcvd9yfcw0/alsi-0.jpg' },
        { name: 'Ginger', description: 'Ginger is a warm, aromatic rhizome used across Indian kitchens. Its lively flavour makes it a familiar choice for teas, curries, and traditional preparations.', image: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?auto=format&fit=crop&w=500&q=80' },
        { name: 'Dhania', description: 'Coriander is valued for both its fresh leaves and fragrant seeds. It brings a citrusy, earthy character to cooking and traditional home preparations.', image: 'https://onemg.gumlet.io/images/aajb2xlk0rrf1ihnfssk/dhania-0.jpg' },
        { name: 'Fennel Seeds', description: 'Fennel seeds, also called saunf, have a sweet, cooling aroma. They are commonly enjoyed after meals or steeped into a fragrant herbal infusion.', image: 'https://onemg.gumlet.io/images/tx3eulyzgfldbt7igzke/fennel-seeds-0.jpg' },
        { name: 'Bael', description: 'Bael is a traditional Indian fruit with a distinctive fragrant pulp. It appears in seasonal drinks, preserves, and a variety of heritage recipes.', image: 'https://onemg.gumlet.io/images/ayywlnwbshdwibuotbfj/bael-0.jpg' },
    ] },
    { title: 'Hair Care', items: [
        { name: 'Onion', description: 'Onion is a kitchen staple that also features in many traditional hair rituals. Its sharp aroma and rich colour make it instantly recognisable.', image: 'https://onemg.gumlet.io/images/ezfdfqum4v4j5eve0sqo/onion-0.jpg' },
        { name: 'Bhringraj', description: 'Bhringraj is a leafy botanical long associated with classic Ayurvedic hair-care traditions. It is commonly recognised in oils and herbal blends.', image: 'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=500&q=80' },
        { name: 'Amla', description: 'Indian gooseberry, known as amla, is a tangy green fruit found in many traditional oils and botanical blends. Its bright, fresh character makes it a timeless favourite.', image: 'https://onemg.gumlet.io/images/irazjokdgsiiuw6abiph/amla-0.jpg' },
        { name: 'Shikakai', description: 'Shikakai is a pod-based botanical used in traditional cleansing rituals. It is often powdered and combined with other herbs in hair-care routines.', image: 'https://onemg.gumlet.io/images/jjuvxnubrxztnibqkp8w/shikakai-0.jpg' },
        { name: 'Mehendi', description: 'Henna, or mehendi, is cherished in Indian beauty and festive traditions. Its leaves are traditionally made into natural colour and decorative pastes.', image: '/assets/download.jfif' },
    ] },
    { title: 'Skin Care', items: [
        { name: 'Aloe Vera', description: 'Aloe vera is a succulent with thick, moisture-rich leaves and clear inner gel. It is a familiar plant in simple, plant-based skin-care routines.', image: 'https://static.wixstatic.com/media/ad0cb5_2a24903de1f244f6b69395e78b749405~mv2_d_2478_1859_s_2.jpg/v1/fill/w_640,h_1296,al_c,q_90,enc_avif,quality_auto/ad0cb5_2a24903de1f244f6b69395e78b749405~mv2_d_2478_1859_s_2.jpg' },
        { name: 'Honey', description: 'Honey is a golden, naturally fragrant pantry favourite. Its rich texture has made it a popular ingredient in traditional face packs and home rituals.', image: 'https://onemg.gumlet.io/images/q3lxrcgk8iok8lvx9lap/honey-0.jpg' },
        { name: 'Turmeric', description: 'Turmeric is a vivid golden spice used in Indian cooking and beauty traditions. Its distinctive colour and earthy aroma make it instantly recognisable.', image: 'https://onemg.gumlet.io/images/s86txjtecyd8kbcjf7dv/turmeric-0.jpg' },
        { name: 'Coconut', description: 'Coconut is a versatile tropical ingredient used in many everyday self-care rituals. The flesh, water, and oil all have a place in traditional preparations.', image: 'https://onemg.gumlet.io/images/uc2vwlgcfu9x2ylp9v0w/coconut-0.jpg' },
        { name: 'Grapes', description: 'Fresh grapes bring a juicy, naturally refreshing note to skin-care rituals. Their deep purple and green varieties make for a vibrant botanical ingredient.', image: 'https://onemg.gumlet.io/images/gjiscdsvkzjbkcpt8xdw/grapes-0.jpg' },
    ] },
];

let uploaded = false;
const setUploaded = (value: boolean) => { uploaded = value; };

export default function Home() {
    const [query, setQuery] = useState(''); const [tab, setTab] = useState('Medicines'); const [notice, setNotice] = useState(''); const [pin, setPin] = useState(''); const [uploaded, setUploaded] = useState(false); const cart = useCartStore((state) => state.items); const addItem = useCartStore((state) => state.addItem); const setItemQuantity = useCartStore((state) => state.setItemQuantity); const toggleCart = useCartStore((state) => state.toggleCart);
    const filtered = useMemo(() => products.filter(p => `${p.name} ${p.composition}`.toLowerCase().includes(query.toLowerCase())), [query]);
    const substitutes = products.filter(p => p.composition === 'Paracetamol 650mg');
    const add = (p: Product) => { addItem(p); setNotice(`${p.name} added to cart`); setTimeout(() => setNotice(''), 2200); };
    const updateOneMgCart = (product: { id: string; title: string; mrp: number; discountPercent: number; isRxRequired?: boolean; image?: string }, quantity: number) => {
        const price = Number(product.mrp) * (1 - (Number(product.discountPercent) || 0) / 100);
        setItemQuantity({ id: product.id, name: product.title, price, rx: product.isRxRequired, image: product.image }, quantity);
        setNotice(quantity > 0 ? `${product.title} quantity updated` : `${product.title} removed from cart`);
        setTimeout(() => setNotice(''), 2200);
    };
    return <main className={styles.app}>
        <div className={styles.topline}>India&apos;s most trusted healthcare platform <span>Download the app</span></div>
        <header className={styles.header}><div className={styles.nav}><button className={styles.mobileMenu}><Menu size={20} /></button><Link href="/" className={styles.logo}><span>1</span>mg</Link><nav><button className={tab === 'Medicines' ? styles.activeNav : ''} onClick={() => setTab('Medicines')}>Medicines</button><button className={tab === 'Lab Tests' ? styles.activeNav : ''} onClick={() => setTab('Lab Tests')}>Lab Tests</button><button className={tab === 'Doctors' ? styles.activeNav : ''} onClick={() => setTab('Doctors')}>Consult Doctors</button><button className={tab === 'Ayurveda' ? styles.activeNav : ''} onClick={() => setTab('Ayurveda')}>Ayurveda</button></nav><div className={styles.location}><MapPin size={16} /><span>Deliver to <b>110001</b></span><ChevronDown size={14} /></div><UserAuthButton /><button className={styles.cart} onClick={toggleCart} aria-label="Open cart"><ShoppingCart size={19} /><i>{cart.length}</i></button></div><div className={styles.searchWrap}><Search size={20} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search for medicines and health products" /><kbd>⌘ K</kbd></div></header>
        {notice && <div className={styles.toast}>{notice}<X size={15} onClick={() => setNotice('')} /></div>}
        {tab === 'Medicines' && <>
            <section className={styles.content} style={{ paddingBottom: 0 }} aria-label="1mg essentials">
                <div className={styles.sectionHead}><div><p className={styles.eyebrow}>1MG ESSENTIALS</p><h2>Popular health picks</h2></div><span className={styles.muted}>Add products directly to your cart</span></div>
                <div style={{ display: 'grid', gap: 15, gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))' }}>
                    {oneMgProducts.filter((product) => `${product.title} ${product.manufacturer}`.toLowerCase().includes(query.toLowerCase())).map((product) => <OneMgProductCard key={product.id} product={product} onAddToCart={updateOneMgCart} />)}
                </div>
            </section>
            <section className={styles.hero}><div><p className={styles.eyebrow}>YOUR HEALTH, OUR PRIORITY</p><h1>Care that comes<br /><em>home.</em></h1><p className={styles.heroCopy}>Authentic medicines, lab tests and expert care delivered to your door.</p><button className={styles.primary} onClick={() => document.getElementById('catalog')?.scrollIntoView({ behavior: 'smooth' })}>Explore medicines <ArrowRight size={17} /></button></div><div className={styles.heroArt}><div className={styles.sun}></div><div className={styles.bottle}><span>1mg</span><small>DAILY<br />WELLNESS</small></div><div className={styles.heart}>♥</div></div></section>
            <section className={styles.services}><div><ShieldCheck /><b>100% genuine medicines</b><span>Quality you can trust</span></div><div><Activity /><b>Free doctor consultation</b><span>Get expert medical advice</span></div><div><Clock3 /><b>Care at your doorstep</b><span>Same-day delivery available</span></div></section>
            <section className={styles.content} id="catalog"><div className={styles.sectionHead}><div><p className={styles.eyebrow}>CURATED FOR YOU</p><h2>Shop by health concerns</h2></div><span className={styles.muted}>Care tailored to your needs</span></div><div className={styles.healthConcernGrid}>{healthConcerns.map((concern) => <a className={styles.healthConcernCard} key={concern.name} href={concern.href} target="_blank" rel="noreferrer"><img src={concern.image} alt="" /><span>{concern.name}</span></a>)}</div>
                <div className={styles.sectionHead}><div><p className={styles.eyebrow}>POPULAR TODAY</p><h2>Medicines for every need</h2></div><span className={styles.muted}>Showing {filtered.length} products</span></div><div className={styles.productGrid}>{filtered.map(p => <article className={styles.product} key={p.id}><div className={styles.productImage}><SafeImage src={p.image} alt={p.name} width={120} height={140} style={{ objectFit: 'contain' }} />{p.rx && <span className={styles.rx}>Rx</span>}</div><p className={styles.productBrand}>{p.brand}</p><h3>{p.name}</h3><p className={styles.composition}>{p.composition}</p><div className={styles.price}>₹{p.price} <del>₹{p.mrp}</del><span>{Math.round((1 - p.price / p.mrp) * 100)}% off</span></div><button className={styles.addBtn} onClick={() => add(p)}>Add to cart</button></article>)}</div>
            </section>
            <section className={styles.substitute}><div><p className={styles.eyebrow}>SMARTER SAVINGS</p><h2>Find a lower-cost substitute</h2><p>Same active ingredient. Better value. Compare trusted alternatives recommended by our pharmacists.</p><button className={styles.darkBtn} onClick={() => setNotice('Substitute engine found 1 lower-cost option')}>Compare substitutes <ArrowRight size={16} /></button></div><div className={styles.compare}><div className={styles.compareLabel}>PARACETAMOL 650MG</div>{substitutes.slice(0, 2).map((p, i) => <div className={styles.compareRow} key={p.id}><div className={styles.miniPack}>1mg</div><div><b>{p.name}</b><small>{p.brand} · Same composition</small></div><strong>₹{p.price}</strong>{i === 1 && <span className={styles.best}>BEST VALUE</span>}</div>)}</div></section>
        </>}
        {tab === 'Lab Tests' && <Lab pin={pin} setPin={setPin} setNotice={setNotice} />} {tab === 'Doctors' && <Doctors setNotice={setNotice} />} {tab === 'Ayurveda' && <Ayurveda setNotice={setNotice} />}
        <section className={styles.footerCta}><div><HeartPulse size={26} /><b>Health stories, made simple.</b><span>Join 10 million+ people who trust 1mg for their health.</span></div><button className={styles.primary}>Get the app <ArrowRight size={16} /></button></section>
        <footer><div className={styles.logo}><span>1</span>mg</div><span>© 2026 Tata 1mg · Care for all.</span><div>Privacy &nbsp; Terms &nbsp; Contact us</div></footer>
    </main>;
}
function Lab({ pin, setPin, setNotice }: { pin: string; setPin: (v: string) => void; setNotice: (v: string) => void }) {
    const [selectedTest, setSelectedTest] = useState('');
    const [selectedDate, setSelectedDate] = useState('');
    const [selectedTime, setSelectedTime] = useState('');
    const [bookedSlot, setBookedSlot] = useState<{ test: string; date: string; time: string } | null>(null);
    const timeSlots = ['07:00 - 08:00', '08:00 - 09:00', '09:00 - 10:00', '10:00 - 11:00', '11:00 - 12:00'];
    const confirmBooking = () => {
        if (!selectedDate || !selectedTime) { setNotice('Please select a collection date and time slot'); return; }
        setBookedSlot({ test: selectedTest, date: selectedDate, time: selectedTime });
        setNotice(`Home collection booked for ${selectedTime}`);
    };
    return <section className={styles.content + ' ' + styles.module}><div className={styles.moduleHero}><div><p className={styles.eyebrow}>DIAGNOSTICS, MADE EASY</p><h1>Know your health.<br /><em>Own your life.</em></h1><p>Book reliable lab tests with free home sample collection and digital reports.</p></div><div className={styles.labArt}><FlaskConical size={80} /></div></div><div className={styles.sectionHead}><div><p className={styles.eyebrow}>POPULAR PACKAGES</p><h2>Tests people love</h2></div><span className={styles.muted}>Free home collection</span></div><div className={styles.testGrid}>{['Full Body Checkup', 'Thyroid Profile', 'Diabetes Care', 'Vitamin Health'].map((name, i) => <article className={styles.test} key={name}><span><FlaskConical size={20} /></span><h3>{name}</h3><p>{i + 18} parameters covered</p><b>₹{699 + i * 200}</b><button className={styles.addBtn} onClick={() => { setSelectedTest(name); setSelectedDate(''); setSelectedTime(''); }}>Book now <ArrowRight size={15} /></button></article>)}</div>
        {selectedTest && <section aria-label="Choose collection slot" style={{ background: '#fff7f5', border: '1px solid #ffd5cf', borderRadius: 6, marginBottom: 28, padding: 24 }}><p className={styles.eyebrow}>SCHEDULE HOME COLLECTION</p><h3 style={{ fontSize: 21, fontWeight: 400, margin: '0 0 8px' }}>{selectedTest}</h3><p style={{ color: '#706c66', font: '13px Arial', margin: '0 0 18px' }}>Choose a convenient date and a one-hour collection window.</p><label style={{ color: '#444', display: 'block', font: '12px Arial', fontWeight: 'bold', marginBottom: 16 }}>COLLECTION DATE<input type="date" value={selectedDate} onChange={event => setSelectedDate(event.target.value)} style={{ border: '1px solid #d9d5cc', display: 'block', font: '14px Arial', marginTop: 7, padding: 10 }} /></label><p style={{ color: '#444', font: '12px Arial', fontWeight: 'bold', margin: '0 0 9px' }}>AVAILABLE TIME SLOTS</p><div style={{ display: 'flex', flexWrap: 'wrap', gap: 9, marginBottom: 19 }}>{timeSlots.map(time => <button key={time} type="button" onClick={() => setSelectedTime(time)} style={{ background: selectedTime === time ? '#ff6f61' : '#fff', border: '1px solid #ff6f61', borderRadius: 4, color: selectedTime === time ? '#fff' : '#d85145', cursor: 'pointer', font: '12px Arial', padding: '9px 12px' }}>{time}</button>)}</div><button className={styles.darkBtn} type="button" onClick={confirmBooking}>Confirm collection slot <Check size={15} /></button></section>}
        {bookedSlot && <section aria-live="polite" style={{ background: '#e7f1e9', border: '1px solid #b9d9c0', borderRadius: 6, marginBottom: 28, padding: '16px 20px' }}><p className={styles.eyebrow} style={{ color: '#397347', marginBottom: 7 }}>COLLECTION BOOKED</p><b style={{ fontSize: 15 }}>{bookedSlot.test}</b><p style={{ color: '#3f6046', font: '13px Arial', margin: '7px 0 0' }}>Home sample collection: {new Date(`${bookedSlot.date}T00:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}, {bookedSlot.time}</p></section>}
        <div className={styles.pinCheck}><div><MapPin /><b>Check home collection</b><span>Enter your pincode to see available slots</span></div><input placeholder="Enter pincode" value={pin} onChange={e => setPin(e.target.value)} /><button className={styles.darkBtn} onClick={() => setNotice(pin.length === 6 ? 'Great, home collection is available' : 'Please enter a 6-digit pincode')}>Check</button></div></section> }
function Doctors({ setNotice }: { setNotice: (v: string) => void }) {
    const [selectedDoctor, setSelectedDoctor] = useState<typeof doctors[number] | null>(null);
    const [appointmentDate, setAppointmentDate] = useState('');
    const [appointmentTime, setAppointmentTime] = useState('');
    const [confirmedAppointment, setConfirmedAppointment] = useState<{ doctor: string; specialty: string; date: string; time: string } | null>(null);
    const consultationSlots = ['10:00 AM', '11:30 AM', '02:00 PM', '04:30 PM', '07:00 PM'];
    const confirmAppointment = () => {
        if (!selectedDoctor || !appointmentDate || !appointmentTime) { setNotice('Please select a consultation date and time'); return; }
        setConfirmedAppointment({ doctor: selectedDoctor.name, specialty: selectedDoctor.specialty, date: appointmentDate, time: appointmentTime });
        setNotice(`Consultation booked with ${selectedDoctor.name}`);
    };
    return <section className={styles.content + ' ' + styles.module}><div className={styles.doctorHero}><div><p className={styles.eyebrow}>EXPERT CARE, ON CALL</p><h1>A doctor is<br /><em>always here.</em></h1><p>Talk to a qualified doctor in minutes, from wherever you are.</p><button className={styles.primary} onClick={() => setNotice('Showing doctors available now')}>Consult now <Video size={17} /></button></div><div className={styles.doctorArt}><Stethoscope size={86} /></div></div><div className={styles.sectionHead}><div><p className={styles.eyebrow}>TOP SPECIALISTS</p><h2>Find your doctor</h2></div><span className={styles.muted}>Available today</span></div><div className={styles.doctorGrid}>{doctors.map(d => <article className={styles.doctor} key={d.name}><div className={styles.avatar}>{d.name.split(' ').map(x => x[0]).join('')}</div><div><h3>{d.name}</h3><p>{d.specialty}</p><small>{d.exp} experience · ★ {d.rating}</small><div><b>₹{d.fee}</b><button className={styles.addBtn} onClick={() => { setSelectedDoctor(d); setAppointmentDate(''); setAppointmentTime(''); }}>Book slot <CalendarDays size={15} /></button></div></div></article>)}</div>
        {selectedDoctor && <section aria-label="Choose consultation slot" style={{ background: '#fff7f5', border: '1px solid #ffd5cf', borderRadius: 6, marginBottom: 28, padding: 24 }}><p className={styles.eyebrow}>SCHEDULE VIDEO CONSULTATION</p><h3 style={{ fontSize: 21, fontWeight: 400, margin: '0 0 8px' }}>{selectedDoctor.name}</h3><p style={{ color: '#706c66', font: '13px Arial', margin: '0 0 18px' }}>{selectedDoctor.specialty} · ₹{selectedDoctor.fee} consultation</p><label style={{ color: '#444', display: 'block', font: '12px Arial', fontWeight: 'bold', marginBottom: 16 }}>CONSULTATION DATE<input type="date" value={appointmentDate} onChange={event => setAppointmentDate(event.target.value)} style={{ border: '1px solid #d9d5cc', display: 'block', font: '14px Arial', marginTop: 7, padding: 10 }} /></label><p style={{ color: '#444', font: '12px Arial', fontWeight: 'bold', margin: '0 0 9px' }}>AVAILABLE TIME SLOTS</p><div style={{ display: 'flex', flexWrap: 'wrap', gap: 9, marginBottom: 19 }}>{consultationSlots.map(time => <button key={time} type="button" onClick={() => setAppointmentTime(time)} style={{ background: appointmentTime === time ? '#ff6f61' : '#fff', border: '1px solid #ff6f61', borderRadius: 4, color: appointmentTime === time ? '#fff' : '#d85145', cursor: 'pointer', font: '12px Arial', padding: '9px 12px' }}>{time}</button>)}</div><button className={styles.darkBtn} type="button" onClick={confirmAppointment}>Confirm consultation <Check size={15} /></button></section>}
        {confirmedAppointment && <section aria-live="polite" style={{ background: '#e7f1e9', border: '1px solid #b9d9c0', borderRadius: 6, marginBottom: 28, padding: '16px 20px' }}><p className={styles.eyebrow} style={{ color: '#397347', marginBottom: 7 }}>CONSULTATION BOOKED</p><b style={{ fontSize: 15 }}>{confirmedAppointment.doctor} · {confirmedAppointment.specialty}</b><p style={{ color: '#3f6046', font: '13px Arial', margin: '7px 0 0' }}>Video consultation: {new Date(`${confirmedAppointment.date}T00:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}, {confirmedAppointment.time}</p></section>}
        <div className={styles.upload}><div><FileUp /><b>Need a prescription?</b><span>Upload it securely for verification by our pharmacists.</span></div><label className={styles.darkBtn}>{uploaded ? <><Check size={16} /> Uploaded</> : <>Upload prescription <input type="file" hidden onChange={() => setUploaded(true)} /></>}</label></div></section> }

function Ayurveda({ setNotice }: { setNotice: (v: string) => void }) {
    const [selectedCare, setSelectedCare] = useState('Featured Herbs');
    const careCollections = ['Featured Herbs', 'Skin Care', 'Digestive Care', 'Hair Care'];
    return <section className={styles.content + ' ' + styles.module}><div className={styles.ayurvedaHero}><div><p className={styles.eyebrow}>NATURE-LED WELLNESS</p><h1>Rooted in<br /><em>tradition.</em></h1><p>Discover familiar Ayurvedic herbs and everyday care rituals, thoughtfully organised for your wellness routine.</p><a className={styles.primary} href="https://www.1mg.com/ayurveda" target="_blank" rel="noreferrer">Explore Ayurveda <ArrowRight size={17} /></a></div><div className={styles.ayurvedaArt}><Leaf size={88} /></div></div><div className={styles.sectionHead}><div><p className={styles.eyebrow}>FEATURED HERBS</p><h2>Natural favourites</h2></div><span className={styles.muted}>Explore plant-powered essentials</span></div><div className={styles.ayurvedaGrid}>{ayurvedaHighlights.map((item) => <article className={styles.ayurvedaCard} key={item.title}><img src={item.image} alt={item.title} /><span><b>{item.title}</b><small>{item.detail}</small><p>{item.description}</p><button type="button" onClick={() => setNotice(`${item.title} added to your Ayurveda list`)}>Learn more <ArrowRight size={13} /></button></span></article>)}</div><div className={styles.ayurvedaCareSections}>{ayurvedaCareSections.map((section) => <section className={styles.ingredientSection} key={section.title}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>AYURVEDIC INGREDIENTS</p><h2>{section.title}</h2></div><span className={styles.muted}>Explore traditional favourites</span></div><div className={styles.ingredientGrid}>{section.items.map((item) => <article className={styles.ingredientCard} key={item.name}><img src={item.image} alt={item.name} /><h3>{item.name}</h3><p>{item.description}</p><button type="button" onClick={() => setNotice(`${item.name} selected from ${section.title}`)}>Explore <ArrowRight size={13} /></button></article>)}</div></section>)}</div><section className={styles.ayurvedaBrowse}><div><p className={styles.eyebrow}>SHOP BY ROUTINE</p><h2>Ayurveda for every day</h2><p>Choose a care collection to explore traditional ingredients and simple self-care rituals.</p></div><div className={styles.ayurvedaCareList}>{careCollections.map((care) => <button type="button" className={selectedCare === care ? styles.selectedAyurvedaCare : ''} onClick={() => { setSelectedCare(care); setNotice(`${care} collection selected`); }} key={care}>{care}<ArrowRight size={16} /></button>)}</div></section><div className={styles.ayurvedaSelection} aria-live="polite"><Leaf size={21} /><div><b>{selectedCare}</b><span>Explore herbs and Ayurvedic wellness products for this collection.</span></div><a href="https://www.1mg.com/ayurveda" target="_blank" rel="noreferrer">View collection</a></div></section>;
}
