'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { ChevronDown, ChevronLeft, ChevronRight, X } from 'lucide-react';
import images from './images.json';
import styles from './page.module.css';

const doctors=[{name:'Dr. Meera Sharma',specialty:'General Physician',experience:'14 years',fee:399,rating:4.9},{name:'Dr. Rohan Kapoor',specialty:'Dermatologist',experience:'11 years',fee:599,rating:4.8},{name:'Dr. Ananya Iyer',specialty:'Paediatrician',experience:'16 years',fee:499,rating:4.9}];
const reviews=[['The booking steps were easy to follow. I could choose a specialist and a time that suited my day, all from home.','Priya'],['Having the consultation details in one place makes it easier to prepare my questions and keep track of my appointment.','Rahul'],['A simple way to explore specialties and find a convenient consultation slot for a family member.','Ananya']];
const benefits=[['100% confidential discussion','Private Consultation','Discuss your concerns with your doctor. Review the privacy policy before sharing personal health information.'],['Certified doctors consultation','Qualified Doctors','Explore doctors by specialty and experience to find the right professional for your concerns.'],['Seek expert opinion anytime, anywhere','Convenience','Choose a convenient time and access your consultation from home.'],['Affordable, cost effective, and economical','Cost Effective','Compare consultation fees before selecting your doctor. Demo fees start at \u20b9399.']];
const faqs=[['When will I get an answer to my query? What happens if I don\u2019t get a response?','This website currently offers demo scheduling. Selecting a slot does not contact a doctor or guarantee a response.'],['Who are the consulting doctors?','The doctor profiles shown in this demo are sample profiles. A live provider connection is required before real consultations can be booked.'],['Will the doctor be able to resolve my issue?','A clinician can assess your concerns and advise on next steps. Some concerns require an in-person examination. This demo does not provide a medical assessment.'],['Is my consultation private with my doctor?','Read the privacy policy for information about data handling. Avoid entering sensitive medical information in the demo consultation room.'],['For how long is the consultation valid?','The current booking selection is kept in this session. Follow-up periods will depend on the connected consultation provider.'],['Do you have a refund policy?','No consultation payment is collected in this demo. Any future paid consultation will need a clearly stated cancellation and refund policy.']];
const img=(key:string)=>(images as Record<string,string>)[key];
export default function DoctorsPage(){
 const [open,setOpen]=useState(false),[join,setJoin]=useState(false),[query,setQuery]=useState(''),[specialty,setSpecialty]=useState('All'),[sort,setSort]=useState('rating'),[doctor,setDoctor]=useState(''),[date,setDate]=useState(''),[time,setTime]=useState(''),[notice,setNotice]=useState(''),[review,setReview]=useState(0);
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close()},[open]);
 const shown=doctors.filter(d=>(specialty==='All'||d.specialty===specialty)&&(d.name+' '+d.specialty).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='fee'?a.fee-b.fee:b.rating-a.rating);
 function consult(){setJoin(false);setDoctor('');setNotice('');setOpen(true)}
 return <main className={styles.page}>
  <div className={styles.careStrip}><img src="/assets/doctors/5e7341e1-0637-4703-a7dc-aa8ea920769b.png" alt=""/><div><p>Consultation and more benefits with Care Plan membership.</p><Link href="/care-plan"><img src={img('Care Plan Icon')} alt="Care Plan"/><span>Join now!</span></Link></div></div>
  <section className={styles.hero}><div><h1>Online doctor consultation with qualified doctors</h1><p className={styles.price}>Starting at &#8377;399</p><div className={styles.features}>{[['Talk within 30 min','Choose your time'],['Free follow up for 3 days','Private consultation'],['Get a valid prescription','Share your concerns']].map(([icon,label])=><span key={icon}><img src={img(icon)} alt=""/>{label}</span>)}</div><button className={styles.primary} onClick={consult}>Consult now</button></div><img className={styles.heroImage} src={img('alt image')} alt="Doctor consultation from home"/></section>
  <section className={styles.stats} aria-label="Consultation statistics"><div><b>30L+</b><span>Total Consultations</span></div><div><b>3k+</b><span>Daily Consultations</span></div><div><b>22+</b><span>Specialities</span></div></section>
  <section className={styles.reviews}><h2>Our Happy Customers</h2><div className={styles.review}><button aria-label="Previous review" onClick={()=>setReview((review+reviews.length-1)%reviews.length)}><ChevronLeft size={20}/></button><div aria-live="polite"><p>{reviews[review][0]}</p><span>{reviews[review][1]}</span></div><button aria-label="Next review" onClick={()=>setReview((review+1)%reviews.length)}><ChevronRight size={20}/></button></div><small>Sample testimonials for this demonstration.</small></section>
  <section className={styles.benefits}>{benefits.map(([icon,title,text])=><article key={title}><img src={img(icon)} alt=""/><h3>{title}</h3><p>{text}</p></article>)}</section>
  <section className={styles.faq}><h2>Frequently Asked Questions</h2>{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={19}/></summary><p>{a}</p></details>)}</section>
  <section className={styles.join}><img src={img('Doctor')} alt="Doctor"/><div><h2>Are you a doctor ?</h2><p>Be a part of our panel of specialists and connect with your patients from anywhere.</p><button className={styles.primary} onClick={()=>{setJoin(true);setOpen(true)}}>Join Now</button></div></section>
  <dialog ref={dialog} className={styles.dialog} aria-labelledby="doctor-dialog-title" onCancel={()=>setOpen(false)} onClick={e=>{if(e.target===e.currentTarget)setOpen(false)}}><button className={styles.close} aria-label="Close" onClick={()=>setOpen(false)}><X size={22}/></button><h2 id="doctor-dialog-title">{join?'Join our doctor panel':doctor?'Choose a consultation slot':'Find the right specialist'}</h2>
   {join?<><p>Doctor registration is not connected yet. Visit our help page for the available support options.</p><Link className={styles.primary} href="/help" onClick={()=>setOpen(false)}>Visit help</Link></>:doctor?<form onSubmit={e=>{e.preventDefault();setNotice(`Selected ${date} at ${time} with ${doctor}. This is a demo; no appointment has been sent.`)}}><p>{doctor}</p><p className={styles.note}>Demo scheduling: this selection stays in the current session.</p><label>Date<input type="date" required min={new Date().toLocaleDateString('en-CA')} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<select required value={time} onChange={e=>setTime(e.target.value)}><option value="">Choose a time</option>{['10:00 AM','11:30 AM','02:00 PM','04:30 PM','07:00 PM'].map(t=><option key={t}>{t}</option>)}</select></label><button className={styles.primary}>Confirm selection</button><button type="button" className={styles.back} onClick={()=>{setDoctor('');setNotice('')}}>Back to doctors</button>{notice&&<p role="status">{notice} <Link href="/consultation/demo">Open consultation room</Link></p>}</form>:<><p className={styles.note}>Sample profiles and demo scheduling.</p><div className={styles.filters}><input placeholder="Search specialty or doctor" aria-label="Search doctors" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Specialty" value={specialty} onChange={e=>setSpecialty(e.target.value)}><option>All</option>{doctors.map(d=><option key={d.specialty}>{d.specialty}</option>)}</select><select aria-label="Sort doctors" value={sort} onChange={e=>setSort(e.target.value)}><option value="rating">Highest rated</option><option value="fee">Lowest fee</option></select></div><div className={styles.results}>{shown.map(d=><article key={d.name}><div className={styles.avatar}>{d.name.split(' ').slice(1).map(n=>n[0]).join('')}</div><div><h3>{d.name}</h3><p>{d.specialty}</p><p>{d.experience} experience &middot; &#9733; {d.rating}</p></div><div><b>&#8377;{d.fee}</b><button className={styles.primary} onClick={()=>{setDoctor(d.name);setNotice('')}}>Book slot</button></div></article>)}</div>{!shown.length&&<p role="status">No matching doctors.</p>}</>}
  </dialog>
 </main>
}
