'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { FormEvent, useState } from 'react';
import { ArrowLeft, Check, LockKeyhole, Mail, ShieldCheck, UserRound } from 'lucide-react';
import { useHealthStore } from '../../lib/store';
import { apiFetch, readApiError } from '../../lib/api';
import { useCartStore } from '../../lib/useCartStore';
import styles from './login.module.css';

export default function LoginPage() {
 const [signup, setSignup] = useState(false); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const setSession = useHealthStore((state) => state.setSession); const loadCart = useCartStore((state) => state.loadCart); const router = useRouter();
 const submit = async (event: FormEvent) => { event.preventDefault(); setMessage(''); if (signup && password.length < 8) { setMessage('Use a password with at least 8 characters.'); return; } try { const response = await apiFetch(`/auth/${signup ? 'register' : 'login'}`, { method: 'POST', body: signup ? { name, email, password } : { email, password } }); if (!response.ok) { setMessage(await readApiError(response, `Unable to continue (server returned ${response.status}). Please try again.`)); return; } const payload = await response.json(); if (signup) { setMessage(payload.message); return; } setSession({ email: payload.user.email, name: payload.user.name }); await loadCart(); router.push('/'); } catch { setMessage('Unable to connect to the server. Please try again.'); } };
 return <main className={styles.page}><Link href="/" className={styles.back}><ArrowLeft size={16}/> Back to 1mg</Link><section className={styles.shell}><div className={styles.brandPanel}><div className={styles.brandLogo}><span>1</span>mg</div><p className={styles.kicker}>CARE, CONNECTED</p><h1>Your health<br/><em>belongs here.</em></h1><p className={styles.brandCopy}>One secure place for medicines, lab reports and trusted medical advice.</p><div className={styles.trust}><ShieldCheck size={19}/><span><b>Trusted by 10 million+</b><small>families across India</small></span></div></div><div className={styles.formPanel}><div className={styles.formIntro}><p className={styles.kicker}>WELCOME TO 1MG</p><h2>{signup ? 'Create your account' : 'Welcome back'}</h2><p>{signup ? 'Start your simpler health journey today.' : 'Log in to continue your health journey.'}</p></div><div className={styles.tabs}><button className={!signup ? styles.selected : ''} onClick={() => { setSignup(false); setMessage(''); }}>Log in</button><button className={signup ? styles.selected : ''} onClick={() => { setSignup(true); setMessage(''); }}>Sign up</button></div><form onSubmit={submit}>{signup && <label><UserRound size={17}/><span><small>FULL NAME</small><input required placeholder="Your full name" value={name} onChange={(event) => setName(event.target.value)}/></span></label>}<label><Mail size={17}/><span><small>EMAIL ADDRESS</small><input required type="email" placeholder="you@example.com" value={email} onChange={(event) => setEmail(event.target.value)}/></span></label><label><LockKeyhole size={17}/><span><small>PASSWORD</small><input required minLength={6} type="password" placeholder="At least 6 characters" value={password} onChange={(event) => setPassword(event.target.value)}/></span></label>{!signup && <button type="button" className={styles.forgot}>Forgot password?</button>}<button className={styles.submit}>{signup ? 'Create my account' : 'Continue'} <Check size={16}/></button></form>{message && <p className={styles.message}>{message}</p>}<p className={styles.legal}>By continuing, you agree to our <u>Terms of service</u> and <u>Privacy policy</u>.</p></div></section></main>;
}
