'use client';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { FormEvent,Suspense,useEffect,useState } from 'react';
import { X } from 'lucide-react';
import { useHealthStore } from '../../lib/store';
import { useCartStore } from '../../lib/useCartStore';
import { apiFetch,readApiError } from '../../lib/api';
import styles from './login.module.css';
function LoginContent(){const params=useSearchParams();const [signup,setSignup]=useState(params.get('mode')==='signup'),[step,setStep]=useState(0),[slide,setSlide]=useState(params.get('mode')==='signup'?1:0),[email,setEmail]=useState(''),[name,setName]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[success,setSuccess]=useState(false);const router=useRouter(),setSession=useHealthStore(s=>s.setSession),loadCart=useCartStore(s=>s.loadCart);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')router.push('/')};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[router]);
 function switchMode(){setSignup(!signup);setSlide(signup?0:1);setStep(0);setMessage('');setPassword('');setSuccess(false)}
 async function submit(e:FormEvent){e.preventDefault();setMessage('');if(!step){setStep(1);return}setBusy(true);try{const r=await apiFetch('/auth/'+(signup?'register':'login'),{method:'POST',body:signup?{name,email,password}:{email,password}});if(!r.ok)throw Error(await readApiError(r,'Unable to continue'));const data=await r.json();if(signup){setSuccess(true);setMessage(data.message);return}setSession({name:data.user.name,email:data.user.email});try{await loadCart()}catch{}const next=new URLSearchParams(location.search).get('next');router.push(next?.startsWith('/')&&!next.startsWith('//')?next:'/')}catch(e){setMessage(e instanceof Error?e.message:'Unable to connect. Please try again.')}finally{setBusy(false)}}
 return <main className={styles.page}><section className={styles.shell} aria-labelledby="auth-heading"><Link href="/" className={styles.close} aria-label="Close login"><X size={18}/></Link><div className={styles.illustration}><img src={slide===0?'/assets/auth/healthcare.png':'/assets/auth/medicines.png'} alt="" width={140} height={140}/><h2>{slide===0?'Make Healthcare Simpler':'Know Your Medicines'}</h2><p>{slide===0?'Get medicine information, order medicines, book lab tests and consult doctors online from the comfort of your home.':'View medicine information like usage, side effects and cheaper substitutes before you take them.'}</p><div className={styles.dots}>{[0,1].map(i=><button key={i} className={i===slide?styles.selected:''} aria-label={'Show introduction '+(i+1)} aria-pressed={i===slide} onClick={()=>setSlide(i)}/>)}</div></div><div className={styles.formPanel}><h1 id="auth-heading">{signup?'Sign Up':'Login'}</h1><p className={styles.intro}>{signup?'Create your account with email to get started.':'Get access to your orders, lab tests & doctor consultations'}</p><form onSubmit={submit}><div className={styles.fields}><label><span>Email address</span><input autoFocus required type="email" autoComplete="email" placeholder="Enter your email address" value={email} onChange={e=>setEmail(e.target.value)} readOnly={step===1&&success}/></label>{step===1&&<>{signup&&<label><span>Full name</span><input required autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name"/></label>}<label><span>Password</span><input required type="password" autoComplete={signup?'new-password':'current-password'} minLength={signup?8:1} value={password} onChange={e=>setPassword(e.target.value)} placeholder={signup?'At least 8 characters':'Enter your password'}/></label></>}{message&&<p role={success?'status':'alert'} className={success?styles.success:styles.error}>{message}</p>}</div><button className={styles.submit} disabled={busy||success}>{busy?'Please wait…':step===0?'Continue':signup?'Create account':'Login'}</button></form><p className={styles.switch}>{signup?'Already on 1mg ?':'New on 1mg ?'} <button onClick={switchMode}>{signup?'Login':'Sign Up'}</button></p><p className={styles.legal}>By continuing, you agree to our<br/><Link href="/terms">Terms and Conditions</Link> &amp; <Link href="/privacy">Privacy policy</Link></p><Link className={styles.help} href="/help">Need Help? Get in touch</Link></div></section></main>
}

export default function LoginPage(){return <Suspense fallback={<main className={styles.page}>Loading?</main>}><LoginContent/></Suspense>}
