'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useCartStore } from '../lib/useCartStore';
import { useHealthStore } from '../lib/store';
import { SafeImage } from './SafeImage';
import styles from './ProductCard.module.css';
export type CatalogueProduct={id:string;name:string;brand:string;composition?:string;category:string;price:number;mrp:number;stock:number;image:string;isRxRequired?:boolean;description?:string};
export function ProductCard({product}:{product:CatalogueProduct}){const update=useCartStore(s=>s.setItemQuantity),quantity=useCartStore(s=>s.items.find(i=>i.id===product.id)?.quantity||0),session=useHealthStore(s=>s.session),router=useRouter();const [busy,setBusy]=useState(false),[error,setError]=useState('');async function change(n:number){if(!session){router.push('/login');return}setBusy(true);setError('');try{await update({id:product.id,name:product.name,price:product.price,image:product.image,rx:product.isRxRequired},n)}catch(e){setError(e instanceof Error?e.message:'Unable to update cart')}finally{setBusy(false)}}const discount=product.mrp>product.price?Math.round((1-product.price/product.mrp)*100):0;return <article className={styles.card}><Link href={'/products/'+product.id} className={styles.image}><SafeImage src={product.image||'/assets/product-placeholder.svg'} alt={product.name} width={160} height={160}/></Link><Link className={styles.name} href={'/products/'+product.id}>{product.name}</Link><p className={styles.pack}>{product.brand}</p>{product.isRxRequired&&<span className={styles.rx}>Prescription required</span>}<p className={styles.stock}>{product.stock>0?'In stock':'Out of stock'}</p><div className={styles.price}><b>₹{Number(product.price).toLocaleString('en-IN')}</b>{discount>0&&<><del>₹{Number(product.mrp)}</del><span>{discount}% off</span></>}</div>{quantity?<div className={styles.counter}><button aria-label={'Decrease '+product.name} disabled={busy} onClick={()=>change(quantity-1)}>−</button><span>{quantity}</span><button aria-label={'Increase '+product.name} disabled={busy||quantity>=product.stock} onClick={()=>change(quantity+1)}>+</button></div>:<button className={styles.add} disabled={busy||!product.stock} onClick={()=>change(1)}>{busy?'Adding…':'ADD'}</button>}{error&&<p role="alert" className={styles.error}>{error}</p>}</article>}
